export const USERS = [
    {
      id: 1,
      surname: 'Üstek',
      name: 'Serhat',
      phone: '34256453214',
      adress: 'İstanbul/Maltepe',
      age: '28',
      photo: 'https://xsgames.co/randomusers/assets/avatars/male/63.jpg',
      gender: 'Erkek',
    },
    {
      id: 2,
      surname: 'Kızılay',
      name: 'Zeynep',
      phone: '2323232332',
      adress: 'Ankara/Altındağ',
      age: '26',
      photo:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fHww',
      gender: 'Kadın',
    },
    {
      id: 3,
      surname: 'Türkyılmaz',
      name: 'Hasan',
      phone: '2323232332',
      adress: 'İzmir/Karşıyaka',
      age: '23',
      photo: 'https://xsgames.co/randomusers/assets/avatars/male/74.jpg',
      gender: 'Erkek',
    },
    {
      id: 4,
      surname: 'Sarı',
      name: 'Ahmet',
      phone: "3213123121",
      adress: 'Gaziantep/Nizip',
      age: '23',
      photo: null,
      gender: 'Erkek',
    },
  ];